# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_hire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractor',
            name='category',
        ),
    ]
