# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_hire', '0002_remove_tractor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractor',
            name='location_id',
        ),
    ]
