# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_hire', '0003_remove_tractor_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tractor',
            name='location_id',
            field=models.CharField(default=datetime.datetime(2019, 7, 11, 11, 25, 35, 523537, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
